version: "3.9"

services:

  vueapp:
    container_name: vueapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:8000'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vueapp69.rule=Host(`vueapp69.localhost`)"
      - "traefik.http.routers.vueapp69.entrypoints=web"
    networks:
      - net5

  my_frontend:
    container_name: my_frontend
    image: node:lts
    working_dir: /var/www/html/app/
    entrypoint: /bin/bash
    ports:
      - "8089:8090"
    volumes:
      - ./:/var/www/html/app
    tty: true
    command:
      -  "npm run serve"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tt.rule=Host(`tt.localhost`)"
      - "traefik.http.routers.tt.entrypoints=web"
    networks:
      - net5

networks:
  net5:
    name: symapi_net5
    external: true